Revert "Port to Python 3 - fix TypeError"
This reverts commit b7403232ee74a6ba2ce1363c51b762ae54a43028.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/share/sugar/activities/Pippy.activity/collabwrapper.py", line 845, in _received_cb
    self._activity_cb(buddy, msg)
  File "/usr/share/sugar/activities/Pippy.activity/collabwrapper.py", line 315, in __received_cb
    ACTIVITY_FT_MIME)
  File "/usr/share/sugar/activities/Pippy.activity/collabwrapper.py", line 745, in __init__
    self._blob = blob.encode('utf-8')
AttributeError: 'bytes' object has no attribute 'encode'

Signed-off-by: James Cameron <quozl@laptop.org>